### ISSUE TITLE
403 when trying the api for snapshot ( https://opendata.adsb.fi/api/v2/snapshot ) 

### ISSUE THREAD

**Issue by laabak84** [adsbfi/opendata#2]
I am feeding, and i can see that my feeder is registered by visiting adsb.fi on the bottom left corner - "You are feeding".

But when visiting https://opendata.adsb.fi/api/v2/snapshot - i get error 403. 

Am i doing something wrong?

**Comment by tmantti** [comment]
Please contact us via email for individual assistance
